export const BROWSE_CARS = [
  {
    id: 1,
    name: "Tesla Model S Plaid",
    price: "$129,990",
    image: "https://images.pexels.com/photos/3802508/pexels-photo-3802508.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "0 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "San Francisco, CA",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Performance"],
  },
  {
    id: 2,
    name: "BMW i8 Roadster",
    price: "$148,495",
    image: "https://images.pexels.com/photos/3136673/pexels-photo-3136673.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "1,200 miles",
    fuel: "Hybrid",
    transmission: "Auto",
    location: "Los Angeles, CA",
    aiGenerated: false,
    tags: ["Hybrid", "Sports", "Convertible"],
  },
  {
    id: 3,
    name: "Porsche Taycan Turbo S",
    price: "$185,000",
    image: "https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "500 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "Miami, FL",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Performance"],
  },
  {
    id: 4,
    name: "Lamborghini Huracán",
    price: "$208,571",
    image: "https://images.pexels.com/photos/2365572/pexels-photo-2365572.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "800 miles",
    fuel: "Gasoline",
    transmission: "Auto",
    location: "New York, NY",
    aiGenerated: false,
    tags: ["Gasoline", "Supercar", "Performance"],
  },
  {
    id: 5,
    name: "Audi e-tron GT",
    price: "$102,400",
    image: "https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "0 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "Seattle, WA",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Sedan"],
  },
  {
    id: 6,
    name: "Mercedes-AMG GT",
    price: "$118,600",
    image: "https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "2,100 miles",
    fuel: "Gasoline",
    transmission: "Auto",
    location: "Chicago, IL",
    aiGenerated: false,
    tags: ["Gasoline", "Sports", "Coupe"],
  },
];

export const FILTERS = {
  priceRange: ["Under $50k", "$50k - $100k", "$100k - $200k", "Over $200k"],
  fuelType: ["Electric", "Hybrid", "Gasoline"],
  transmission: ["Auto", "Manual"],
};

export type Car = typeof BROWSE_CARS[0];