export const BROWSE_CARS = [
  {
    id: 1,
    name: "Tesla Model S Plaid",
    price: "$129,990",
    image: "https://images.pexels.com/photos/3802508/pexels-photo-3802508.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "0 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "San Francisco, CA",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Performance"],
  },
  {
    id: 2,
    name: "BMW i8 Roadster",
    price: "$148,495",
    image: "https://images.pexels.com/photos/3136673/pexels-photo-3136673.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "1,200 miles",
    fuel: "Hybrid",
    transmission: "Auto",
    location: "Los Angeles, CA",
    aiGenerated: false,
    tags: ["Hybrid", "Sports", "Convertible"],
  },
  {
    id: 3,
    name: "Porsche Taycan Turbo S",
    price: "$185,000",
    image: "https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "500 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "Miami, FL",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Performance"],
  },
  {
    id: 4,
    name: "Lamborghini Huracán",
    price: "$208,571",
    image: "https://images.pexels.com/photos/2365572/pexels-photo-2365572.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "800 miles",
    fuel: "Gasoline",
    transmission: "Auto",
    location: "New York, NY",
    aiGenerated: false,
    tags: ["Gasoline", "Supercar", "Performance"],
  },
  {
    id: 5,
    name: "Audi e-tron GT",
    price: "$102,400",
    image: "https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2024,
    mileage: "0 miles",
    fuel: "Electric",
    transmission: "Auto",
    location: "Seattle, WA",
    aiGenerated: true,
    tags: ["Electric", "Luxury", "Sedan"],
  },
  {
    id: 6,
    name: "Mercedes-AMG GT",
    price: "$118,600",
    image: "https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=800",
    year: 2023,
    mileage: "2,100 miles",
    fuel: "Gasoline",
    transmission: "Auto",
    location: "Chicago, IL",
    aiGenerated: false,
    tags: ["Gasoline", "Sports", "Coupe"],
  },
];


export const BROWSE_CARS_v2 = [
  {
    id: "1",
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    description:
      "The Tesla Model S Plaid is a high-performance electric sedan with cutting-edge technology and luxury features.",
    price: 129990,
    year: 2024,
    mileage: 0,
    fuelType: "ELECTRIC",
    transmission: "AUTO",
    type: "SEDAN",
    location: "San Francisco, CA",
    images: [
      "https://images.pexels.com/photos/3802508/pexels-photo-3802508.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["Black"],
    features: ["Autopilot", "Premium sound", "Heated seats"],
    isNew: true,
    isSold: false,
    isFeatured: true,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
  {
    id: "2",
    name: "BMW i8 Roadster",
    brand: "BMW",
    description:
      "The BMW i8 Roadster is a hybrid sports convertible offering futuristic design and thrilling performance.",
    price: 148495,
    year: 2023,
    mileage: 1200,
    fuelType: "HYBRID",
    transmission: "AUTO",
    type: "CONVERTIBLE",
    location: "Los Angeles, CA",
    images: [
      "https://images.pexels.com/photos/3136673/pexels-photo-3136673.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["Blue", "Silver"],
    features: ["Convertible roof", "Hybrid drive", "Navigation system"],
    isNew: false,
    isSold: false,
    isFeatured: false,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
  {
    id: "3",
    name: "Porsche Taycan Turbo S",
    brand: "Porsche",
    description:
      "The Porsche Taycan Turbo S is an all-electric luxury performance sedan with breathtaking acceleration.",
    price: 185000,
    year: 2024,
    mileage: 500,
    fuelType: "ELECTRIC",
    transmission: "AUTO",
    type: "SEDAN",
    location: "Miami, FL",
    images: [
      "https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["White"],
    features: ["Fast charging", "Sport Chrono Package", "Luxury interior"],
    isNew: true,
    isSold: false,
    isFeatured: true,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
  {
    id: "4",
    name: "Lamborghini Huracán",
    brand: "Lamborghini",
    description:
      "The Lamborghini Huracán is a gasoline-powered Italian supercar built for extreme performance and style.",
    price: 208571,
    year: 2023,
    mileage: 800,
    fuelType: "GASOLINE",
    transmission: "AUTO",
    type: "SUPERCAR",
    location: "New York, NY",
    images: [
      "https://images.pexels.com/photos/2365572/pexels-photo-2365572.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["Yellow", "Green"],
    features: ["Carbon ceramic brakes", "Track mode", "Sport exhaust"],
    isNew: false,
    isSold: false,
    isFeatured: false,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
  {
    id: "5",
    name: "Audi e-tron GT",
    brand: "Audi",
    description:
      "The Audi e-tron GT is an electric luxury sedan blending sportiness with comfort and everyday usability.",
    price: 102400,
    year: 2024,
    mileage: 0,
    fuelType: "ELECTRIC",
    transmission: "AUTO",
    type: "SEDAN",
    location: "Seattle, WA",
    images: [
      "https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["Silver", "Black"],
    features: ["Quattro all-wheel drive", "Matrix LED lights", "Panoramic roof"],
    isNew: true,
    isSold: false,
    isFeatured: true,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
  {
    id: "6",
    name: "Mercedes-AMG GT",
    brand: "Mercedes-Benz",
    description:
      "The Mercedes-AMG GT is a gasoline-powered sports coupe combining German engineering and luxury.",
    price: 118600,
    year: 2023,
    mileage: 2100,
    fuelType: "GASOLINE",
    transmission: "AUTO",
    type: "COUPE",
    location: "Chicago, IL",
    images: [
      "https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    colors: ["Red", "Grey"],
    features: ["AMG performance exhaust", "Adaptive suspension", "Sport seats"],
    isNew: false,
    isSold: false,
    isFeatured: false,
    createdAt: "2025-09-04T10:25:58.403Z",
    updatedAt: "2025-09-04T10:25:58.403Z",
    userId: "demo-user",
  },
];




export const FILTERS = {
  priceRange: ["Under $50k", "$50k - $100k", "$100k - $200k", "Over $200k"],
  fuelType: ["ELECTRIC", "HYBRID", "GASOLINE"],
  transmission: ["AUTO", "MANUAL"],
};

export type Car = typeof BROWSE_CARS_v2[0];